server_name: odysseus-core
port: 4222
http_port: 8222
jetstream {
  store_dir: "/data/jetstream"
  max_mem_store: 1GB
  max_file_store: 20GB
}
authorization {
  users: [
    { user: $NATS_USER, password: $NATS_PASSWORD }
  ]
}
